{{- if .Values.podDisruptionBudget.enabled -}}
{{- $fullName := include "deep-learning-hpc-demo.fullname" . -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullName }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deep-learning-hpc-demo.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "deep-learning-hpc-demo.selectorLabels" . | nindent 6 }}
{{- end }}