{{- $fullName := include "deep-learning-hpc-demo.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deep-learning-hpc-demo.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}