apiVersion: v1
kind: Service
metadata:
  name: {{ include "deep-learning-hpc-demo.fullname" . }}
  labels:
    {{- include "deep-learning-hpc-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "deep-learning-hpc-demo.selectorLabels" . | nindent 4 }}